### ISSUE TITLE
tmp/ vs /work

### ISSUE THREAD

**Issue by radare** [radare/radare2-release#7]
symlink tmp/radare2-* to work/ ?

**Comment by radare** [comment]
cc @brainstorm

**Comment by brainstorm** [comment]
Hmm... a bit more context/motivation behind this please? :-S

**Comment by radare** [comment]
inside the docker images the directory where the source of the program you are building is /work, but this directory is mounted from ./tmp/radare2-${VERSION}

this is “confusing” and it will be more intuitive to have a symlink or so
